on:
  push:
    branches: "**"
  # workflow_dispatch:
name: Label approved pull requests
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false
    # - name: Label when approved
    #   # if: ${{ !contains(github.event.pull_request.labels.*.name, 'Do Not Merge') }}
    #   uses: pullreminders/label-when-approved-action@master
    #   env:
    #     APPROVALS: "0"
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     ADD_LABEL: "bug"
    #     REMOVE_LABEL: "invalid"
    - name: Add Labels
  # You may pin to the exact commit or the version.
  # uses: christianvuerings/add-labels@ede518da81f427f037b828421aa08c239bfc7f47
      uses: christianvuerings/add-labels@v1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
    # Labels to add
        labels: "bug"
